#!/usr/bin/python
print("demonstration of arbitrary integer precision")
print("with the exponential factorial")
print ("a1 = 1**0 = %d" % (1**0))
print ("a2 = 2**1 = %d" % (2**1))
x = str( 3**2 )
print ("a3 = 3**2 = %s and has %i digits" % (x,len(x)))
y = str( 4**int(x) )
print ("a4 = 4**3**2 = 4**%s = %s and has %i digits" % (x,y,len(y)))
print("this may take a while...")
z = str( 5**int(y) )
print ("a5 = 5**4**3**2 = 5**%s = %s...%s and has %i digits" % (y,z[:20], z[-20:],len(z)))
